### PR TITLE
Remove blanket State<T> implementation for T: Encode + Decode

### PR DESCRIPTION
**Pull request by cwlittle**
Replaces blanket State implementation with individual implementations for specific types for more custom behavior

### CODE REVIEW

**Comment by cwlittle** [comment]
This is blocked by necessary pin to head of PR that has some necessary ed changes for orga current dev. Once that gets merged, my ed changes can be merged into develop there, and Cargo.toml conflicts can be resolved here.

**Comment by cwlittle** [comment]
There are a lot of places in the newer developments where we bank on the fact that the blanket State implementation is there for types that implement Encode and Decode. This may involve modifications to the state derive macro before the derives can be cleanly added.

**Comment by cwlittle** [comment]
This will need the State derive macro to support generic, bounded arguments

**Comment by mappum** [comment]
> This will need the State derive macro to support generic, bounded arguments

This requires fixing #32, done in #83

**Comment by cwlittle** [comment]
A bit of scope creep here, but since State implementation doesn't make much sense with Option considering that variant switching from Some -> None -> Some will not flush in-between switches cause final Some value to retain values from the store. However, the idea of removing the blanket implementation of State<T> for T: Encode + Decode will make the system more resistant to change in the future. This PR being pivoted to that purpose.

**Pull request merged**
